#!/bin/bash

g++ `pkg-config --cflags opencv` photo.cpp MagicTool.o\
    `pkg-config --libs opencv` --std=c++17 -o ../photo -O3\
    -I Headers/

g++ `pkg-config --cflags opencv` video.cpp MagicTool.o\
    `pkg-config --libs opencv` --std=c++17 -o ../video -O3\
    -I Headers/
