#!/bin/bash

cd magic

while [ -n "$1" ]
do
  case "$1" in
    all)       echo -e "magic is being built..." &&\
            g++ `pkg-config --cflags opencv ` magic.cpp -c `pkg-config --libs opencv` --std=c++17 -O3\
            && echo -e "magic is ready\n" &&\
            \
               echo -e "photo is being built..." &&\
            g++ `pkg-config --cflags opencv` photo.cpp magic.o `pkg-config --libs opencv` -o ../photo --std=c++17 -O3\
            && echo -e "photo is ready\n" &&\
            \
               echo -e "video is being built..." &&\
            g++ `pkg-config --cflags opencv` video.cpp magic.o `pkg-config --libs opencv` -o ../video --std=c++17 -O3\
            && echo -e "video is ready\n" &&\
            \
               echo -e "trans is being built..." &&\
            g++ `pkg-config --cflags opencv` trans.cpp magic.o `pkg-config --libs opencv` -o ../trans --std=c++17 -O3\
            && echo -e "trans is ready\n";;
    
    magic)     echo -e "magic is being built..." &&\
            g++ `pkg-config --cflags opencv ` magic.cpp -c `pkg-config --libs opencv` --std=c++17 -O3\
            && echo -e "magic is ready\n";;

    photo)     echo -e "photo is being built..." &&\
            g++ `pkg-config --cflags opencv` photo.cpp magic.o `pkg-config --libs opencv` -o ../photo --std=c++17 -O3\
            && echo -e "photo is ready\n";;

    video)     echo -e "video is being built..." &&\
            g++ `pkg-config --cflags opencv` video.cpp magic.o `pkg-config --libs opencv` -o ../video --std=c++17 -O3\
            && echo -e "video is ready\n";;

    trans)     echo -e "trans is being built..." &&\
            g++ `pkg-config --cflags opencv` trans.cpp magic.o `pkg-config --libs opencv` -o ../trans --std=c++17 -O3\
            && echo -e "trans is ready\n";;
    *);;
  esac
  shift
done
